services:
  kafka:
    image: apache/kafka-native:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    restart: unless-stopped
    networks:
      - kafka-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - kafka-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - kafka-network

volumes:
  mongodb_data:

networks:
  kafka-network:
    driver: bridge